// statements.js
export const casual = [
    "Who is the funniest person in the group?",
    "Who would survive the longest on a deserted island?",
    "Who is most likely to become famous?",
    "Who would make the best secret agent?",
    "Who is the worst at keeping secrets?",
    "Who would be the best stand-up comedian?",
    "Who is most likely to start a successful business?",
    "Who is the most adventurous person here?",
    "Who would make the best detective?",
    "Who is most likely to become president?",
    "Who would be the best at escaping from prison?",
    "Who would win a reality TV show?",
    "Who has the most interesting hidden talent?",
    "Who is most likely to write a best-selling book?",
    "Who is the best storyteller?",
    "Who would be the best at surviving a zombie apocalypse?",
    "Who has the best dance moves?",
    "Who is most likely to become a millionaire?",
    "Who would be the best at leading a revolution?",
    "Who is the most dramatic person in the group?",
    "Who is the biggest prankster?",
    "Who would be the best at negotiating a hostage situation?",
    "Who is most likely to go viral on social media?",
    "Who would be the best at defusing a bomb?",
    "Who is the best liar in the group?",
    "Who would be the best at acting in a movie?",
    "Who is most likely to travel the world?",
    "Who would be the best at running a marathon?",
    "Who has the best poker face?",
    "Who is most likely to become a professional athlete?",
    "Who would be the best at cooking a gourmet meal?",
    "Who would be the best at surviving in the wild?",
    "Who has the best fashion sense?",
    "Who is most likely to adopt 10 dogs?",
    "Who would be the best at solving a mystery?",
    "Who is the most likely to embarrass themselves in public?",
    "Who would be the best at planning a surprise party?",
    "Who has the most contagious laugh?",
    "Who is most likely to become a billionaire?",
    "Who is the most likely to break a world record?",
    "Who is the best at making new friends?",
    "Who would be the best at skydiving?",
    "Who would be the best at escaping a haunted house?",
    "Who is the most likely to end up in a viral fail video?",
    "Who would be the best at solving a Rubik's Cube?",
    "Who is most likely to have a secret identity?",
    "Who would be the best at living off the grid?",
    "Who is the most likely to run for mayor?",
    "Who would be the best at breaking into a bank (hypothetically)?",
    "Who is the most likely to have a hidden talent?",
    "Who would be the best at negotiating with aliens?",
    "Who is the most likely to get lost on a road trip?",
    "Who would be the best at training a wild animal?",
    "Who is the most likely to get kicked out of a party?",
    "Who would be the best at surviving an alien invasion?",
    "Who is the most likely to become a professional gamer?",
    "Who would be the best at learning a new language?",
    "Who is the most likely to get caught sneaking into a movie?",
    "Who would be the best at designing a new fashion trend?",
    "Who is the most likely to have the craziest conspiracy theories?",
    "Who would be the best at running a five-star restaurant?",
    "Who is the most likely to accidentally go viral?",
    "Who would be the best at making a last-minute decision?",
    "Who is the most likely to have an unusual phobia?",
    "Who would be the best at swimming with sharks?",
    "Who is the most likely to start their own cult (as a joke)?",
    "Who would be the best at creating an internet meme?",
    "Who is the most likely to get caught cheating at a board game?",
    "Who would be the best at living in the medieval era?",
    "Who is the most likely to be a professional stunt double?",
    "Who would be the best at hacking into a computer system?",
    "Who is the most likely to own a secret underground lair?",
    "Who would be the best at working as a private investigator?",
    "Who is the most likely to join a circus?",
    "Who would be the best at making up a convincing excuse?",
    "Who is the most likely to find a hidden treasure?",
    "Who would be the best at building a spaceship?",
    "Who is the most likely to accidentally start a fire?",
    "Who would be the best at teaching a robot emotions?",
    "Who is the most likely to forget their own birthday?",
    "Who would be the best at creating a viral dance challenge?",
    "Who is the most likely to get arrested for a ridiculous reason?",
    "Who would be the best at reading minds?",
    "Who is the most likely to get stuck in an elevator?",
    "Who would be the best at crafting a fake identity?",
    "Who is the most likely to have an unusual collection?",
    "Who would be the best at surviving in ancient times?",
    "Who is the most likely to start a food fight?",
    "Who would be the best at inventing a new holiday?",
    "Who is the most likely to become a ghost hunter?",
    "Who would be the best at escaping from a locked room?",
    "Who is the most likely to accidentally adopt a wild animal?",
    "Who would be the best at discovering a new planet?",
    "Who is the most likely to have a famous doppelgänger?",
    "Who would be the best at pretending to be a celebrity?",
    "Who is the most likely to wake up with no memory of the night before?",
    "Who would be the best at creating a successful YouTube channel?",
    "Who is the most likely to take a trip to space?",
    "Who would be the best at befriending a celebrity?",
    "Who is the most likely to make a major scientific breakthrough?",
    "Who would be the best at convincing people they are a time traveler?",
    "Who is the most likely to come up with a genius invention?",
    "Who would be the best at running a detective agency?",
    "Who is the most likely to accidentally reveal a government secret?"
];
