export const edgy = [
    "Who would sell their soul for fame?",
    "Who is most likely to fake a relationship for clout?",
    "Who in this group has main character syndrome?",
    "Who would be the most dangerous if given unlimited power?",
    "Who would die first in an apocalypse?",
    "Who is most likely to become a dictator?",
    "Who would be the most likely to manipulate the masses?",
    "Who would betray their best friend for a billion dollars?",
    "Who in this group has the most villain potential?",
    "Who would be the best at gaslighting someone?",
    "Who would be the most dangerous mastermind if they turned evil?",
    "Who is most likely to not make it to old age?",
    "Who in this group has the darkest thoughts?",
    "Who would be the most likely to disappear forever?",
    "Who in this group has the most unresolved trauma?",
    "Who is most likely to develop a serious addiction?",
    "Who in this group would party too hard and regret it?",
    "Who is most likely to drink the most and blackout?",
    "Who would be the first to use illegal substances?",
    "Who in this group is secretly addicted to drugs?",
    "Who in this group has the biggest personal demons?",
    "Who would be the most unstable under pressure?",
    "Who in this group is most likely to have a complete meltdown?",
    "Who in this group is most likely to self-destruct?",
    "Who is most likely to cheat on their partner?",
    "Who in this group would break someone's heart the worst?",
    "Who is most likely to fake love for money?",
    "Who in this group would ghost someone after a long relationship?",
    "Who would be the first to abandon their family for selfish reasons?",
    "Who is most likely to manipulate their significant other?",
    "Who in this group has the most toxic traits?",
    "Who would be the first to emotionally destroy someone?",
    "Who in this group would fake a disability for sympathy?",
    "Who in this group would post something online that ruins their career?",
    "Who in this group has no moral boundaries?",
    "Who in this group would survive the longest in a full-scale war?",
    "Who in this group would rule with fear?",
    "Who is most likely to flirt their way out of trouble?",
    "Who in this group would make the best sugar baby?",
    "Who in this group would make the best sugar mommy?",
    "Who in this group has the most scandalous secret?",
    "Who would start an OnlyFans?",
    "Who is most likely to start an OnlyFans?",
    "Who in this group has the biggest commitment issues?",
    "Who in this group would fall in love with a stranger instantly?",
    "Who is most likely to date someone twice their age?",
    "Who in this group has the most exes?",
    "Who would be the first to kiss a stranger at a party?",
    "Who in this group has the worst taste in partners?",
    "Who is most likely to have a one-night stand?",
    "Who in this group has the highest body count?",
    "Who is most likely to date multiple people at once?",
    "Who in this group would be the best in bed?",
    "Who in this group would be the worst in bed?",
    "Who in this group has the wildest dating history?",
    "Who is most likely to date someone just for their looks?",
    "Who is most likely to send nudes to someone they just met?",
    "Who in this group is most likely to experiment with their sexuality?",
    "Who would be the first to fall for a rebound relationship?",
    "Who in this group is most likely to regret a hookup?",
    "Who here has the darkest secret?",
    "Who would ghost everyone and vanish?",
    "Who lies the most?",
    "Who starts drama just for fun?",
    "Who would stab a friend in the back?",
    "Who would get arrested first?",
    "Who is most likely to be banned from a country?",
    "Who would leak someone's secrets?",
    "Who would fake a pregnancy?",
    "Who would sabotage a relationship?",
    "Who would sleep with a friend's partner?",
    "Who would expose a secret for likes?",
    "Who would be canceled online?",
    "Who would commit fraud?",
    "Who would become a cult leader?",
    "Who would use a fake identity?",
    "Who would bribe their way to success?",
    "Who would sleep their way to the top?",
    "Who dates only for money?",
    "Who would sell our secrets to the media?",
    "Who would get plastic surgery and lie about it?",
    "Who is the biggest narcissist?",
    "Who would fake their own death?",
    "Who has the messiest breakups?",
    "Who stalks their exes online?",
    "Who would ruin a wedding out of jealousy?",
    "Who secretly wants to be famous?",
    "Who would lie under oath?",
    "Who would start a pyramid scheme?",
    "Who thrives on chaos?",
    "Who is most likely to be in a toxic relationship?",
    "Who can't keep a secret?",
    "Who would do anything for money?",
    "Who is the most emotionally unavailable?",
    "Who pretends to be someone they’re not?",
    "Who would fake being rich?",
    "Who always plays the victim?",
    "Who would steal someone’s spotlight?",
    "Who is the most manipulative?",
    "Who holds grudges forever?",
    "Who secretly judges everyone?",
    "Who gossips the most?",
    "Who is always involved in drama?",
    "Who ruins group trips?",
    "Who would ghost their own family?",
    "Who thrives on attention?",
    "Who lies the most during games?",
    "Who always needs to be right?",
    "Who is most likely to snap one day?",
    "Who is the most two-faced?",
    "Who secretly hates someone here?",
    "Who is the most jealous?",
    "Who would date someone for revenge?",
    "Who is most likely to fake being spiritual?",
    "Who would secretly date their friend's crush?",
    "Who is the biggest hypocrite?",
    "Who posts thirst traps for validation?",
    "Who cheats during board games?",
    "Who can’t be trusted with secrets?",
    "Who would punch a wall when angry?",
    "Who picks fights for no reason?",
    "Who acts innocent but isn’t?",
    "Who is secretly the freakiest?",
    "Who would crash a party they weren’t invited to?",
    "Who has the worst intentions?",
    "Who is most likely to lie to their therapist?",
    "Who flirts with everyone?",
    "Who can't handle criticism?",
    "Who talks behind everyone's back?",
    "Who would sell someone out to save themselves?",
    "Who is a total drama magnet?",
    "Who lies about their past?",
    "Who always plays dumb to get out of trouble?",
    "Who brags the most?",
    "Who thinks they’re better than everyone?",
    "Who pretends to like people they hate?",
    "Who would lie to win a game?",
    "Who cares too much about their image?",
    "Who exaggerates everything?",
    "Who is secretly competitive?",
    "Who would go to jail and pretend it was cool?",
    "Who would become a sugar daddy/mommy?",
    "Who would ghost their partner without explanation?",
    "Who would lie about a pregnancy?",
    "Who would fake being sick for attention?",
    "Who is most likely to manipulate a whole group?",
    "Who has the messiest private life?",
    "Who is always in a love triangle?",
    "Who secretly stalks people online?",
    "Who gets jealous when not invited?",
    "Who creates fake accounts to spy?",
    "Who cries to get what they want?",
    "Who thinks they are always the victim?",
    "Who acts like a saint but isn’t?",
    "Who would betray someone over a small grudge?",
    "Who holds power in this group without anyone knowing?",
    "Who plays people against each other?",
    "Who is most likely to be famous for something controversial?",
    "Who is most likely to be on reality TV?",
    "Who would blackmail someone?",
    "Who in this group has the least empathy?",
    "Who is the most secretive?",
    "Who do you trust the least?",
    "Who hides their true personality the best?",
    "Who in this group is most likely to be a scammer?",
    "Who is always caught up in gossip?",
    "Who is most likely to befriend someone for clout?"
  ];
  