export const edgy = [
    "Who would sell their soul for fame?",
    "Who is most likely to fake a relationship for clout?",
    "Who in this group has main character syndrome?",
    "Who would be the most dangerous if given unlimited power?",
    "Who would die first in an apocalypse?", // 
    "Who is most likely to become a dictator?",
    "Who would be the most likely to manipulate the masses?",
    "Who would betray their best friend for a billion dollars?",
    "Who in this group has the most villain potential?",
    "Who would be the best at gaslighting someone?",
    "Who would be the most dangerous mastermind if they turned evil?",
    "Who is most likely to not make it to old age?",
    "Who in this group has the darkest thoughts?",
    "Who would be the most likely to disappear forever?",
    "Who in this group has the most unresolved trauma?",
    "Who is most likely to develop a serious addiction?",
    "Who in this group would party too hard and regret it?",
    "Who is most likely to drink the most and blackout?",
    "Who would be the first to use illegal substances?",
    "Who in this group is secretly addicted to drugs?",
    "Who in this group has the biggest personal demons?",
    "Who would be the most unstable under pressure?",
    "Who in this group is most likely to have a complete meltdown?",
    "Who in this group is most likely to self-destruct?",
    "Who is most likely to cheat on their partner?",
    "Who in this group would break someone's heart the worst?",
    "Who is most likely to fake love for money?",
    "Who in this group would ghost someone after a long relationship?",
    "Who would be the first to abandon their family for selfish reasons?",
    "Who is most likely to manipulate their significant other?",
    "Who in this group has the most toxic traits?",
    "Who would be the first to emotionally destroy someone?",
    "Who in this group would fake a disability for sympathy?",
    "Who in this group would post something online that ruins their career?",
    "Who in this group has no moral boundaries?",
    "Who in this group would survive the longest in a full-scale war?",
    "Who in this group would rule with fear?",
    "Who is most likely to flirt their way out of trouble?",
    "Who in this group would make the best sugar baby?",
    "Who in this group would make the best sugar mommy?",
    "Who in this group has the most scandalous secret?",
    "Who would start an OnlyFans?",
    "WWho is most likely to start an OnlyFans?",
    "Who in this group has the biggest commitment issues?",
    "Who in this group would fall in love with a stranger instantly?",
    "Who is most likely to date someone twice their age?",
    "Who in this group has the most exes?",
    "Who would be the first to kiss a stranger at a party?",
    "Who in this group has the worst taste in partners?",
    "Who is most likely to have a one-night stand?",
    "Who in this group has the highest body count?",
    "Who is most likely to date multiple people at once?",
    "Who in this group would be the best in bed?",
    "Who in this group would be the worst in bed?",
    "Who in this group has the wildest dating history?",
    "Who is most likely to date someone just for their looks?",
    "Who is most likely to send nudes to someone they just met?",
    "Who in this group is most likely to experiment with their sexuality?",
    "Who would be the first to fall for a rebound relationship?",
    "Who in this group is most likely to regret a hookup?",
]