export const overshare = [
    "Who would you vote out of the group?",
    "Who is most likely to drink and drive?",
    "Who would only help someone if it's recorded?",
    "Who in the group is most likely to betray you?",
    "Who has a hidden talent that they should keep hidden?",
    "Who likes feet?",
    "Who do you least expect to help you?",
    "Who has been raised the worst?",
    "Who would make the worst parent?",
    "Who has the best parents?",
    "Who has had the worst childhood?",
    "Who will start the 3th reich?",
    "If you where a can, who could drink you?",
    "Who is most likely to kill a whole family?",
    "Who would ghost everyone and vanish?",
    "Who is most likely to cry during sex?",
    "Who would secretly enjoy being publicly humiliated?",
    "Who would hook up with someone for revenge?",
    "Who’s most likely to fall in love with a criminal?",
    "Who’s hiding something big from the group?",
]